[feature] Added support for openwisp_notifications
openwisp/ansible-openwisp2 pull request #215
Opened 2020-11-02 09:58 UTC by pandafy

- [x] Added support for openwisp_notifications integration in openwisp_controller
 - [ ] Updated docs to ask user to update Site object
 - [ ] Added message to ask user to update Site object when role completes execution
 - [ ] Updated tests to run integration tests for notifications

Fixes #214 

--------

Blocked by:
 - [ ] https://github.com/openwisp/openwisp-controller/pull/316 -  Refactoring of routes and URLs of openwisp_notifications

------

I have used this playbook for manually testing this patch on Ubuntu 20.04

```
- hosts: openwisp2
  become: "{{ become | default('yes') }}"
  roles:
    - openwisp.openwisp2
  vars:
    openwisp2_controller_pip: https://github.com/pandafy/openwisp-controller/tarball/fix-notification-settings
    openwisp2_extra_python_packages:
      - django-flat-json-widget
      - https://github.com/openwisp/openwisp-notifications/tarball/master
    openwisp2_default_from_email: "openwisp2@openwisp2.mydomain.com"
```

2020-11-02 10:17 UTC, TravisBuddy commented
## Travis tests have failed

Hey @pandafy,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 3rd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;ansible-openwisp2&#x2F;jobs&#x2F;740798283">View build log</a>


<details>
  <summary>
    <strong>
     molecule test
    </strong>
  </summary>

```
--> Test matrix
    
└── default
    ├── dependency
    ├── lint
    ├── cleanup
    ├── destroy
    ├── syntax
    ├── create
    ├── prepare
    ├── converge
    ├── idempotence
    ├── side_effect
    ├── verify
    ├── cleanup
    └── destroy
    
--> Scenario: 'default'
--> Action: 'dependency'
    Starting galaxy role install process
    - extracting Stouts.postfix to /home/travis/.cache/molecule/ansible-openwisp2/default/roles/Stouts.postfix
    - Stouts.postfix (origin/develop) was installed successfully
Dependency completed successfully.
Skipping, missing the requirements file.
--> Scenario: 'default'
--> Action: 'lint'
--> Executing: set -e
yamllint . || true
ansible-lint || true
./defaults/main.yml
  1:1       warning  missing document start "---"  (document-start)
  88:34     warning  truthy value should be one of [false, true]  (truthy)
  89:34     warning  truthy value should be one of [false, true]  (truthy)

./molecule/default/molecule.yml
  31:30     warning  truthy value should be one of [false, true]  (truthy)

./molecule/local/molecule.yml
  45:30     warning  truthy value should be one of [false, true]  (truthy)

./molecule/resources/verify.yml
  5:11      warning  truthy value should be one of [false, true]  (truthy)
  6:17      warning  truthy value should be one of [false, true]  (truthy)

./meta/main.yml
  18:3      error    wrong indentation: expected 4 but found 2  (indentation)
  23:5      error    wrong indentation: expected 6 but found 4  (indentation)
  29:5      error    wrong indentation: expected 6 but found 4  (indentation)

./tasks/nginx.yml
  1:1       warning  missing document start "---"  (document-start)
  16:161    warning  line too long (174 > 160 characters)  (line-length)
  22:11     warning  truthy value should be one of [false, true]  (truthy)
  27:4      error    wrong indentation: expected 4 but found 3  (indentation)

./tasks/variables.yml
  1:1       warning  missing document start "---"  (document-start)
  9:15      error    too many spaces after colon  (colons)

./tasks/pip.yml
  1:1       warning  missing document start "---"  (document-start)
  11:31     warning  truthy value should be one of [false, true]  (truthy)
  24:31     warning  truthy value should be one of [false, true]  (truthy)
  62:31     warning  truthy value should be one of [false, true]  (truthy)
  77:31     warning  truthy value should be one of [false, true]  (truthy)
  94:31     warning  truthy value should be one of [false, true]  (truthy)
  108:31    warning  truthy value should be one of [false, true]  (truthy)
  122:31    warning  truthy value should be one of [false, true]  (truthy)
  135:31    warning  truthy value should be one of [false, true]  (truthy)
  149:31    warning  truthy value should be one of [false, true]  (truthy)
  163:31    warning  truthy value should be one of [false, true]  (truthy)
  176:31    warning  truthy value should be one of [false, true]  (truthy)
  190:31    warning  truthy value should be one of [false, true]  (truthy)
  204:31    warning  truthy value should be one of [false, true]  (truthy)
  218:31    warning  truthy value should be one of [false, true]  (truthy)

./tasks/variables-spatialite.yml
  1:1       warning  missing document start "---"  (document-start)

./tasks/django.yml
  1:1       warning  missing document start "---"  (document-start)
  21:14     warning  truthy value should be one of [false, true]  (truthy)
  95:11     warning  truthy value should be one of [false, true]  (truthy)
  118:14    warning  truthy value should be one of [false, true]  (truthy)
  124:11    warning  truthy value should be one of [false, true]  (truthy)

./tasks/supervisor.yml
  1:1       warning  missing document start "---"  (document-start)

./tasks/complete.yml
  1:1       warning  missing document start "---"  (document-start)

./tasks/apt.yml
  1:1       warning  missing document start "---"  (document-start)
  23:18     warning  truthy value should be one of [false, true]  (truthy)
  35:18     warning  truthy value should be one of [false, true]  (truthy)
  45:18     warning  truthy value should be one of [false, true]  (truthy)
  57:15     warning  truthy value should be one of [false, true]  (truthy)
  77:18     warning  truthy value should be one of [false, true]  (truthy)
  91:18     warning  truthy value should be one of [false, true]  (truthy)

./tasks/selinux.yml
  6:12      warning  truthy value should be one of [false, true]  (truthy)
  7:17      warning  truthy value should be one of [false, true]  (truthy)

./tasks/django_secret_key.yml
  1:1       warning  missing document start "---"  (document-start)

./vars/main.yml
  1:1       warning  missing document start "---"  (document-start)

--> Scenario: 'default'
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
--> Scenario: 'default'
--> Action: 'destroy'
--> Sanity checks: 'docker'
    
    PLAY [Destroy] *****************************************************************
    
    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=openwisp2-debian10)
    
    TASK [Wait for instance(s) deletion to complete] *******************************
    FAILED - RETRYING: Wait for instance(s) deletion to complete (300 retries left).
    ok: [localhost] => (item={'started': 1, 'finished': 0, 'ansible_job_id': '614275295763.5822', 'results_file': '/home/travis/.ansible_async/614275295763.5822', 'changed': True, 'failed': False, 'item': {'command': '', 'image': 'geerlingguy/docker-debian10-ansible:latest', 'name': 'openwisp2-debian10', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}, 'ansible_loop_var': 'item'})
    
    TASK [Delete docker network(s)] ************************************************
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
    
--> Scenario: 'default'
--> Action: 'syntax'
    
    playbook: /home/travis/build/openwisp/ansible-openwisp2/molecule/resources/converge.yml
--> Scenario: 'default'
--> Action: 'create'
    
    PLAY [Create] ******************************************************************
    
    TASK [Log into a Docker registry] **********************************************
    skipping: [localhost] => (item={'command': '', 'image': 'geerlingguy/docker-debian10-ansible:latest', 'name': 'openwisp2-debian10', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}) 
    
    TASK [Check presence of custom Dockerfiles] ************************************
    ok: [localhost] => (item={'command': '', 'image': 'geerlingguy/docker-debian10-ansible:latest', 'name': 'openwisp2-debian10', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']})
    
    TASK [Create Dockerfiles from image names] *************************************
    skipping: [localhost] => (item={'command': '', 'image': 'geerlingguy/docker-debian10-ansible:latest', 'name': 'openwisp2-debian10', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}) 
    
    TASK [Discover local Docker images] ********************************************
    ok: [localhost] => (item={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False', 'item': {'command': '', 'image': 'geerlingguy/docker-debian10-ansible:latest', 'name': 'openwisp2-deb [...]

2020-11-03 21:28 UTC, TravisBuddy commented
Hey @pandafy,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;ansible-openwisp2&#x2F;builds&#x2F;741231593">View build log</a>

###### TravisBuddy Request Identifier: 73052780-1e1b-11eb-b069-4b84fe73ac29

2020-11-05 02:20 UTC, nemesisdesign commented on defaults/main.yml
> +openwisp2_notifications_delete_old_notifications: 90
don't forget to add these two new variables in the [Role Variables docs](https://github.com/openwisp/ansible-openwisp2#role-variables)

2020-11-05 08:13 UTC, TravisBuddy commented
Hey @pandafy,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;ansible-openwisp2&#x2F;builds&#x2F;741572972">View build log</a>

###### TravisBuddy Request Identifier: c203bb70-1f3e-11eb-bd2e-17a8c440c3de

2020-11-06 01:41 UTC, TravisBuddy commented
## Travis tests have failed

Hey @pandafy,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;ansible-openwisp2&#x2F;jobs&#x2F;741735163">View build log</a>


<details>
  <summary>
    <strong>
     molecule test
    </strong>
  </summary>

```
--> Test matrix
    
└── default
    ├── dependency
    ├── lint
    ├── cleanup
    ├── destroy
    ├── syntax
    ├── create
    ├── prepare
    ├── converge
    ├── idempotence
    ├── side_effect
    ├── verify
    ├── cleanup
    └── destroy
    
--> Scenario: 'default'
--> Action: 'dependency'
    Starting galaxy role install process
    - extracting Stouts.postfix to /home/travis/.cache/molecule/ansible-openwisp2/default/roles/Stouts.postfix
    - Stouts.postfix (origin/develop) was installed successfully
Dependency completed successfully.
Skipping, missing the requirements file.
--> Scenario: 'default'
--> Action: 'lint'
--> Executing: set -e
yamllint . || true
ansible-lint || true
./defaults/main.yml
  1:1       warning  missing document start "---"  (document-start)
  88:34     warning  truthy value should be one of [false, true]  (truthy)
  90:34     warning  truthy value should be one of [false, true]  (truthy)

./molecule/default/molecule.yml
  31:30     warning  truthy value should be one of [false, true]  (truthy)

./molecule/local/molecule.yml
  45:30     warning  truthy value should be one of [false, true]  (truthy)

./molecule/resources/verify.yml
  5:11      warning  truthy value should be one of [false, true]  (truthy)
  6:17      warning  truthy value should be one of [false, true]  (truthy)

./meta/main.yml
  18:3      error    wrong indentation: expected 4 but found 2  (indentation)
  23:5      error    wrong indentation: expected 6 but found 4  (indentation)
  29:5      error    wrong indentation: expected 6 but found 4  (indentation)

./tasks/nginx.yml
  1:1       warning  missing document start "---"  (document-start)
  16:161    warning  line too long (174 > 160 characters)  (line-length)
  22:11     warning  truthy value should be one of [false, true]  (truthy)
  27:4      error    wrong indentation: expected 4 but found 3  (indentation)

./tasks/variables.yml
  1:1       warning  missing document start "---"  (document-start)
  9:15      error    too many spaces after colon  (colons)

./tasks/pip.yml
  1:1       warning  missing document start "---"  (document-start)
  11:31     warning  truthy value should be one of [false, true]  (truthy)
  24:31     warning  truthy value should be one of [false, true]  (truthy)
  62:31     warning  truthy value should be one of [false, true]  (truthy)
  77:31     warning  truthy value should be one of [false, true]  (truthy)
  94:31     warning  truthy value should be one of [false, true]  (truthy)
  108:31    warning  truthy value should be one of [false, true]  (truthy)
  122:31    warning  truthy value should be one of [false, true]  (truthy)
  135:31    warning  truthy value should be one of [false, true]  (truthy)
  149:31    warning  truthy value should be one of [false, true]  (truthy)
  163:31    warning  truthy value should be one of [false, true]  (truthy)
  176:31    warning  truthy value should be one of [false, true]  (truthy)
  190:31    warning  truthy value should be one of [false, true]  (truthy)
  204:31    warning  truthy value should be one of [false, true]  (truthy)
  218:31    warning  truthy value should be one of [false, true]  (truthy)

./tasks/variables-spatialite.yml
  1:1       warning  missing document start "---"  (document-start)

./tasks/django.yml
  1:1       warning  missing document start "---"  (document-start)
  21:14     warning  truthy value should be one of [false, true]  (truthy)
  98:11     warning  truthy value should be one of [false, true]  (truthy)
  121:14    warning  truthy value should be one of [false, true]  (truthy)
  127:11    warning  truthy value should be one of [false, true]  (truthy)

./tasks/supervisor.yml
  1:1       warning  missing document start "---"  (document-start)

./tasks/complete.yml
  1:1       warning  missing document start "---"  (document-start)
  15:1      error    too many blank lines (2 > 0)  (empty-lines)

./tasks/apt.yml
  1:1       warning  missing document start "---"  (document-start)
  23:18     warning  truthy value should be one of [false, true]  (truthy)
  35:18     warning  truthy value should be one of [false, true]  (truthy)
  45:18     warning  truthy value should be one of [false, true]  (truthy)
  57:15     warning  truthy value should be one of [false, true]  (truthy)
  77:18     warning  truthy value should be one of [false, true]  (truthy)
  91:18     warning  truthy value should be one of [false, true]  (truthy)

./tasks/selinux.yml
  6:12      warning  truthy value should be one of [false, true]  (truthy)
  7:17      warning  truthy value should be one of [false, true]  (truthy)

./tasks/django_secret_key.yml
  1:1       warning  missing document start "---"  (document-start)

./vars/main.yml
  1:1       warning  missing document start "---"  (document-start)

--> Scenario: 'default'
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
--> Scenario: 'default'
--> Action: 'destroy'
--> Sanity checks: 'docker'
    
    PLAY [Destroy] *****************************************************************
    
    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=openwisp2-ubuntu1804)
    
    TASK [Wait for instance(s) deletion to complete] *******************************
    FAILED - RETRYING: Wait for instance(s) deletion to complete (300 retries left).
    ok: [localhost] => (item={'started': 1, 'finished': 0, 'ansible_job_id': '367908501767.5767', 'results_file': '/home/travis/.ansible_async/367908501767.5767', 'changed': True, 'failed': False, 'item': {'command': '', 'image': 'geerlingguy/docker-ubuntu1804-ansible:latest', 'name': 'openwisp2-ubuntu1804', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}, 'ansible_loop_var': 'item'})
    
    TASK [Delete docker network(s)] ************************************************
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
    
--> Scenario: 'default'
--> Action: 'syntax'
    
    playbook: /home/travis/build/openwisp/ansible-openwisp2/molecule/resources/converge.yml
--> Scenario: 'default'
--> Action: 'create'
    
    PLAY [Create] ******************************************************************
    
    TASK [Log into a Docker registry] **********************************************
    skipping: [localhost] => (item={'command': '', 'image': 'geerlingguy/docker-ubuntu1804-ansible:latest', 'name': 'openwisp2-ubuntu1804', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}) 
    
    TASK [Check presence of custom Dockerfiles] ************************************
    ok: [localhost] => (item={'command': '', 'image': 'geerlingguy/docker-ubuntu1804-ansible:latest', 'name': 'openwisp2-ubuntu1804', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']})
    
    TASK [Create Dockerfiles from image names] *************************************
    skipping: [localhost] => (item={'command': '', 'image': 'geerlingguy/docker-ubuntu1804-ansible:latest', 'name': 'openwisp2-ubuntu1804', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}) 
    
    TASK [Discover local Docker images] ********************************************
    ok: [localhost] => (item={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False', 'item': {'command' [...]

2020-11-07 17:17 UTC, TravisBuddy commented
## Travis tests have failed

Hey @pandafy,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;ansible-openwisp2&#x2F;jobs&#x2F;742106190">View build log</a>


<details>
  <summary>
    <strong>
     molecule test
    </strong>
  </summary>

```
--> Test matrix
    
└── default
    ├── dependency
    ├── lint
    ├── cleanup
    ├── destroy
    ├── syntax
    ├── create
    ├── prepare
    ├── converge
    ├── idempotence
    ├── side_effect
    ├── verify
    ├── cleanup
    └── destroy
    
--> Scenario: 'default'
--> Action: 'dependency'
    Starting galaxy role install process
    - extracting Stouts.postfix to /home/travis/.cache/molecule/ansible-openwisp2/default/roles/Stouts.postfix
    - Stouts.postfix (origin/develop) was installed successfully
Dependency completed successfully.
Skipping, missing the requirements file.
--> Scenario: 'default'
--> Action: 'lint'
--> Executing: set -e
yamllint . || true
ansible-lint || true
./defaults/main.yml
  1:1       warning  missing document start "---"  (document-start)
  88:34     warning  truthy value should be one of [false, true]  (truthy)
  90:34     warning  truthy value should be one of [false, true]  (truthy)

./molecule/default/molecule.yml
  31:30     warning  truthy value should be one of [false, true]  (truthy)

./molecule/local/molecule.yml
  45:30     warning  truthy value should be one of [false, true]  (truthy)

./molecule/resources/verify.yml
  5:11      warning  truthy value should be one of [false, true]  (truthy)
  6:17      warning  truthy value should be one of [false, true]  (truthy)

./meta/main.yml
  18:3      error    wrong indentation: expected 4 but found 2  (indentation)
  23:5      error    wrong indentation: expected 6 but found 4  (indentation)
  29:5      error    wrong indentation: expected 6 but found 4  (indentation)

./tasks/nginx.yml
  1:1       warning  missing document start "---"  (document-start)
  16:161    warning  line too long (174 > 160 characters)  (line-length)
  22:11     warning  truthy value should be one of [false, true]  (truthy)
  27:4      error    wrong indentation: expected 4 but found 3  (indentation)

./tasks/variables.yml
  1:1       warning  missing document start "---"  (document-start)
  9:15      error    too many spaces after colon  (colons)

./tasks/pip.yml
  1:1       warning  missing document start "---"  (document-start)
  11:31     warning  truthy value should be one of [false, true]  (truthy)
  24:31     warning  truthy value should be one of [false, true]  (truthy)
  62:31     warning  truthy value should be one of [false, true]  (truthy)
  77:31     warning  truthy value should be one of [false, true]  (truthy)
  94:31     warning  truthy value should be one of [false, true]  (truthy)
  108:31    warning  truthy value should be one of [false, true]  (truthy)
  122:31    warning  truthy value should be one of [false, true]  (truthy)
  135:31    warning  truthy value should be one of [false, true]  (truthy)
  149:31    warning  truthy value should be one of [false, true]  (truthy)
  163:31    warning  truthy value should be one of [false, true]  (truthy)
  176:31    warning  truthy value should be one of [false, true]  (truthy)
  190:31    warning  truthy value should be one of [false, true]  (truthy)
  204:31    warning  truthy value should be one of [false, true]  (truthy)
  218:31    warning  truthy value should be one of [false, true]  (truthy)

./tasks/variables-spatialite.yml
  1:1       warning  missing document start "---"  (document-start)

./tasks/django.yml
  1:1       warning  missing document start "---"  (document-start)
  21:14     warning  truthy value should be one of [false, true]  (truthy)
  98:11     warning  truthy value should be one of [false, true]  (truthy)
  121:14    warning  truthy value should be one of [false, true]  (truthy)
  127:11    warning  truthy value should be one of [false, true]  (truthy)

./tasks/supervisor.yml
  1:1       warning  missing document start "---"  (document-start)

./tasks/complete.yml
  1:1       warning  missing document start "---"  (document-start)
  15:1      error    too many blank lines (2 > 0)  (empty-lines)

./tasks/apt.yml
  1:1       warning  missing document start "---"  (document-start)
  23:18     warning  truthy value should be one of [false, true]  (truthy)
  35:18     warning  truthy value should be one of [false, true]  (truthy)
  45:18     warning  truthy value should be one of [false, true]  (truthy)
  57:15     warning  truthy value should be one of [false, true]  (truthy)
  77:18     warning  truthy value should be one of [false, true]  (truthy)
  91:18     warning  truthy value should be one of [false, true]  (truthy)

./tasks/selinux.yml
  6:12      warning  truthy value should be one of [false, true]  (truthy)
  7:17      warning  truthy value should be one of [false, true]  (truthy)

./tasks/django_secret_key.yml
  1:1       warning  missing document start "---"  (document-start)

./vars/main.yml
  1:1       warning  missing document start "---"  (document-start)

--> Scenario: 'default'
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
--> Scenario: 'default'
--> Action: 'destroy'
--> Sanity checks: 'docker'
    
    PLAY [Destroy] *****************************************************************
    
    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=openwisp2-ubuntu1804)
    
    TASK [Wait for instance(s) deletion to complete] *******************************
    FAILED - RETRYING: Wait for instance(s) deletion to complete (300 retries left).
    ok: [localhost] => (item={'started': 1, 'finished': 0, 'ansible_job_id': '739583495758.5793', 'results_file': '/home/travis/.ansible_async/739583495758.5793', 'changed': True, 'failed': False, 'item': {'command': '', 'image': 'geerlingguy/docker-ubuntu1804-ansible:latest', 'name': 'openwisp2-ubuntu1804', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}, 'ansible_loop_var': 'item'})
    
    TASK [Delete docker network(s)] ************************************************
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
    
--> Scenario: 'default'
--> Action: 'syntax'
    
    playbook: /home/travis/build/openwisp/ansible-openwisp2/molecule/resources/converge.yml
--> Scenario: 'default'
--> Action: 'create'
    
    PLAY [Create] ******************************************************************
    
    TASK [Log into a Docker registry] **********************************************
    skipping: [localhost] => (item={'command': '', 'image': 'geerlingguy/docker-ubuntu1804-ansible:latest', 'name': 'openwisp2-ubuntu1804', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}) 
    
    TASK [Check presence of custom Dockerfiles] ************************************
    ok: [localhost] => (item={'command': '', 'image': 'geerlingguy/docker-ubuntu1804-ansible:latest', 'name': 'openwisp2-ubuntu1804', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']})
    
    TASK [Create Dockerfiles from image names] *************************************
    skipping: [localhost] => (item={'command': '', 'image': 'geerlingguy/docker-ubuntu1804-ansible:latest', 'name': 'openwisp2-ubuntu1804', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}) 
    
    TASK [Discover local Docker images] ********************************************
    ok: [localhost] => (item={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False', 'item': {'command' [...]

2020-11-09 22:15 UTC, TravisBuddy commented
## Travis tests have failed

Hey @pandafy,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 015f9120-22d9-11eb-b1e0-17a3b2b69400

2020-11-12 02:24 UTC, nemesisdesign reviewed
Looks good, although the build is failing for idempotence test, I remember you fixed that, is this branch already up to date @pandafy?

2020-11-12 15:13 UTC, pandafy commented
@nemesisdesign #219 skipped idempotence test for "Install custom OpenWISP 2 Python packages" task which installs packages from variables defined for openwisp modules. In this patch I have used `openwisp2_extra_python_packages` variable to install openwisp-notification due to `--no-deps` flag set in `Install custom OpenWISP 2 Python packages` task.(See #193).

I will update it once new version of openwisp-controller and openwisp-notifications is released.

2020-11-20 00:42 UTC, nemesisdesign reviewed
We'll also need to merge this one https://github.com/openwisp/ansible-openwisp2/pull/194 before or after this.

2020-11-27 18:03 UTC, nemesisdesign requested changes

2020-11-27 18:03 UTC, nemesisdesign commented on molecule/resources/converge.yml
> +      - https://github.com/openwisp/openwisp-notifications/tarball/master
This shouldn't be needed anymore, we should set ow-controller to 0.8 here: https://github.com/openwisp/ansible-openwisp2/blob/master/defaults/main.yml#L4 and network-topology to 0.5

2020-12-02 20:11 UTC, nemesisdesign approved these changes
Great work @pandafy :+1:

2020-12-02 20:12 UTC, nemesisdesign requested changes
Wait a minute, I spotted one thing to correct.

2020-12-02 20:12 UTC, nemesisdesign commented on README.md
> +    openwisp2_django_netjsonconfig_pip: false
mm.. this should have been removed

2020-12-02 20:55 UTC, nemesisdesign approved these changes
Thanks @pandafy :+1: :tada: :+1:

2020-12-02 20:56 UTC, merged