[chores] Added GitHub workflow for CI
openwisp/ansible-openwisp2 pull request #224
Opened 2020-11-27 21:37 UTC by pandafy

- Removed Travis

2020-11-30 15:44 UTC, atb00ker commented
> Add GALAXY_TOKEN secret @nemesisdesign

Interesting, do we want to update from CI?
Because think it's only updated on release! :smile:

2020-11-30 16:01 UTC, pandafy commented
> > Add GALAXY_TOKEN secret @nemesisdesign
> 
> Interesting, do we want to update from CI?
> Because think it's only updated on release!

@atb00ker I added this because it was already present in `.travis.yml`

2020-12-01 21:52 UTC, nemesisdesign requested changes
This should be unblocked and you can complete it.

![Screenshot from 2020-12-01 16-49-57](https://user-images.githubusercontent.com/841044/100801117-8bc6d580-33f5-11eb-9feb-d4f4f7e1abb4.png)

2020-12-01 21:52 UTC, nemesisdesign commented on .github/workflows/ci.yml
> +name: OpenWISP CI Build
let's change the name of this to `Ansible OpenWISP 2 CI Build`

2020-12-02 13:22 UTC, pandafy commented
The build passed with commits on #206 : https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-gotcha

2020-12-02 13:45 UTC, pandafy commented
The build stalled at `TASK [ansible-openwisp2 : Install openwisp2 controller and its dependencies] ***` without pinning `channels_redis` dependency. Since it is something which has been already taken care of in #206, let's merge this and move forward with rest of the work. :smile:

2020-12-02 15:33 UTC, nemesisdesign approved these changes

2020-12-02 15:34 UTC, merged