[minor] Fixed GitHub unchanged files with check annotations
openwisp/ansible-openwisp2 pull request #237
Opened 2020-12-07 19:06 UTC by atb00ker

2020-12-07 19:07 UTC, atb00ker commented
** Still working on this, just tied up with other work! :smile:

2020-12-07 20:42 UTC, nemesisdesign commented
> ** Still working on this, just tied up with other work!

Thank you Ajay! We'll try to help you with this when we can as well.

2020-12-08 20:20 UTC, atb00ker commented
This is ready for review! :smile:

2020-12-08 20:22 UTC, atb00ker commented on meta/main.yml
> +  min_ansible_version: 2.8
Versions below this one are not supported anymore.

2020-12-09 02:47 UTC, nemesisdesign approved these changes
Great! I guess there's nothing we can do for the remaining warnings, but at least now is a lot more readable.

2020-12-09 06:09 UTC, pandafy reviewed
Great work @atb00ker ! LGTM :+1: 

You should be able to silent `[line-length] line too long (174 > 160 characters)` by appending `# yamllint disable-line rule:line-length`.  

Please read [this section in the yamllint documentation](https://yamllint.readthedocs.io/en/stable/disable_with_comments.html#disabling-checks-for-a-specific-line) for more syntax options

Similarly, you can silent `[truthy] truthy value should be one of [false, true]` using `# yamllint disable-line rule:truthy`.

It can be merged after making these two changes. :smile:

2020-12-09 18:53 UTC, nemesisdesign requested changes
> Great work @atb00ker ! LGTM 
> 
> You should be able to silent `[line-length] line too long (174 > 160 characters)` by appending `# yamllint disable-line rule:line-length`.
> 
> Please read [this section in the yamllint documentation](https://yamllint.readthedocs.io/en/stable/disable_with_comments.html#disabling-checks-for-a-specific-line) for more syntax options
> 
> Similarly, you can silent `[truthy] truthy value should be one of [false, true]` using `# yamllint disable-line rule:truthy`.
> 
> It can be merged after making these two changes.

Thanks for the suggestion @pandafy, @atb00ker, try that when you can so if you succeed we can get rid of all the warnings :+1: :+1:

2020-12-10 14:56 UTC, atb00ker commented
Great this is done, I suppose! :smile:

2020-12-10 15:27 UTC, pandafy approved these changes
LGTM :+1: Thanks @atb00ker.

P.S: I realised that these errors/warning were generated by the [lint step of molecule](https://github.com/openwisp/ansible-openwisp2/runs/1522518589?check_suite_focus=true#step:6:22). GitHub was just putting them here alongside the diff.

2020-12-10 18:58 UTC, nemesisdesign approved these changes
Thank you very much @atb00ker :+1: :+1:

2020-12-10 18:58 UTC, merged