[feature] Add API URLs by default #234
openwisp/ansible-openwisp2 pull request #241
Opened 2020-12-12 10:21 UTC by Purhan

Closes #234

2020-12-12 22:41 UTC, nemesisdesign requested changes
Looks good, will check what's wrong with the build later, in the meanwhile see my comment below please.

2020-12-12 22:41 UTC, nemesisdesign commented on templates/openwisp2/settings.py
> +    'drf_yasg',
I would move these two below, after `rest_framework_gis`

2020-12-13 03:35 UTC, Purhan commented on templates/openwisp2/settings.py
> +    'drf_yasg',
Done

2020-12-13 20:01 UTC, nemesisdesign approved these changes
Thanks!

2020-12-13 20:02 UTC, merged