[deps] Update to celery version 5 #251
openwisp/ansible-openwisp2 pull request #252
Opened 2021-01-06 20:58 UTC by sankha555

The command to launch celery from the command line has been added to README.md according to the changes introduced in celery version 5.0. 

Requesting reviews on this addition and possible changes that should be incorporated.

Fixes #251

2021-01-08 00:57 UTC, nemesisdesign requested changes

2021-01-08 00:57 UTC, nemesisdesign commented on README.md
> +    command_to_start_celery : celery --app openwisp2 worker
this command doesn't do anything, look into the supervisor configuration files, please double check `celery beat` as well.

2021-01-09 07:08 UTC, sankha555 commented
@nemesisdesign I took a look at the ```celery.j2``` and ```celerybeat.j2``` file and the commands mentioned there comply with the ones in the documentation, with a few additional and relevant options. I think that we can close this pull request as it no longer seems relevant.  Meanwhile I think we can work on upgrading monitoring, controlling and radius modules. What do you think about this?

2021-01-11 02:45 UTC, nemesisdesign reviewed
@sankha555 according to this discussion: https://github.com/openwisp/openwisp-notifications/pull/161#discussion_r554447279, this change may not be needed.

Is that's the case? If yes, let's close this.

2021-01-11 05:19 UTC, sankha555 commented
Yes @nemesisdesign , I agree that we can close this. Shall I go ahead and do so (I am actually not sure if I am authorised to close an issue 😅 )?

2021-01-12 02:46 UTC, closed without merging

2021-01-12 02:47 UTC, nemesisdesign commented
@sankha555 you can close your pull requests.