Use django-celery email as default email backend #271
openwisp/ansible-openwisp2 pull request #348
Opened 2022-02-19 21:17 UTC by c4llous

2022-02-22 17:25 UTC, pandafy requested changes
Good start @c4llous. Can you also add `openwisp2_email_backend` to the [Role variables section of the README](https://github.com/openwisp/ansible-openwisp2#role-variables)?  In the short description of the role variable also add link to the [django-celery backend](https://github.com/pmclanahan/django-celery-email) package. 

We also need to add a task that installs `django-celery-backend` in https://github.com/openwisp/ansible-openwisp2/blob/master/tasks/pip.yml. The package should be only installed when `openwisp2_email_backend == "djcelery_email.backends.CeleryEmailBackend"`.

2022-02-22 17:25 UTC, pandafy commented on templates/openwisp2/settings.py
>  {% endif %}
```suggestion
{% endif %}

EMAIL_BACKEND = '{{ openwisp2_email_backend }}'
```

The email backend should not depend on availability of the monitoring module

2022-02-22 17:27 UTC, pandafy requested changes
@c4llous the commit message is not correct, read [OpenWISP's contribution guidelines](https://openwisp.io/docs/developer/contributing.html)

2022-03-17 00:12 UTC, nemesisdesign approved these changes
Thanks @c4llous @pandafy :+1:

2022-03-17 00:12 UTC, merged