[change] Disabled nginx server_tokens #353
openwisp/ansible-openwisp2 pull request #354
Opened 2022-03-04 20:09 UTC by Aryamanz29

Added task in `nginx.yml`, which sets the `server_tokens` to `off`
Closes #353

2022-03-09 14:28 UTC, pandafy requested changes
nginx.conf after running the the role with your changes:

```diff
http {
+server_tokens off;

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;
```

As you can see that there's already a line containing ` server_tokens off;` in the default configuration. But it is commented. I suggest you to update the task, to update that line. 
After which, the nginx.conf will become 

```diff
http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
-        # server_tokens off;
+        server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;
```
Please ask questions if you have any doubts.

2022-03-09 18:20 UTC, Aryamanz29 commented
> 

Can we do something like this? :point_down:  @pandafy 
```bash
- name: disable nginx server tokens
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '#(\s+)server_tokens off'
    replace: 'server_tokens off'
    backup: yes
```

2022-03-10 15:26 UTC, nemesisdesign approved these changes
> ```shell
> - name: disable nginx server tokens
>   replace:
>     path: /etc/nginx/nginx.conf
>     regexp: '#(\s+)server_tokens off'
>     replace: 'server_tokens off'
>     backup: yes
> ```

This works, I will commit this solution now for you, thanks.

2022-03-10 15:57 UTC, nemesisdesign approved these changes

2022-03-10 15:57 UTC, merged