[feature] Added support for Ubuntu 22 #376
openwisp/ansible-openwisp2 pull request #377
Opened 2022-05-05 11:33 UTC by Aryamanz29

Depends on : https://github.com/openwisp/ansible-ow-influxdb/pull/10
Closes #376

2022-05-05 12:54 UTC, Aryamanz29 commented on tasks/freeradius.yml
> +    - ansible_distribution_release|string == 'focal' or ansible_distribution_release|string == 'jammy'
Freeradius package, currently not available for `Ubuntu 22.04 (Jammy Jellyfish)`. 
See this :point_right:  https://networkradius.com/packages/

2022-05-05 21:45 UTC, nemesisdesign requested changes
@Aryamanz29 can you please check what is going on here:

```
  TASK [ansible-openwisp2 : SQL configuration] ***********************************
  fatal: [openwisp2-ubuntu2204]: FAILED! => changed=false 
    checksum: e9e63f34902d5f2a10bd0841cbd95bb821f7e692
    msg: Destination directory /etc/freeradius/mods-available does not exist
```

2022-05-06 20:42 UTC, Aryamanz29 commented
> @Aryamanz29 can you please check what is going on here:
> 
> ```
>   TASK [ansible-openwisp2 : SQL configuration] ***********************************
>   fatal: [openwisp2-ubuntu2204]: FAILED! => changed=false 
>     checksum: e9e63f34902d5f2a10bd0841cbd95bb821f7e692
>     msg: Destination directory /etc/freeradius/mods-available does not exist
> ```
Just checked in `ubuntu22` image
```bash
# ls /etc/freeradius/
3.0
```
because of that, this task fails with error msg `/etc/freeradius/mods-available does not exist`

2022-05-06 20:44 UTC, Aryamanz29 commented on defaults/main.yml
> +freeradius_dir: "{{ '/etc/freeradius/3.0' if ansible_distribution_release|string == 'jammy' else '/etc/freeradius/' }}"
For **ubuntu22 jammy**, `freeradius_dir` should be `/etc/freeradius/3.0`

2022-05-06 21:12 UTC, nemesisdesign requested changes
Looks good! Can you update the line of the README where it says:

```
Tested on Debian (Buster, Bullseye), Ubuntu (18/20 LTS).
```

We can write "Ubuntu (18/20/22 LTS)".

2022-05-06 22:45 UTC, nemesisdesign approved these changes

2022-05-06 22:46 UTC, merged