[change] Updated project URLs to support cloud backends for private storage
openwisp/ansible-openwisp2 pull request #388
Opened 2022-07-21 17:01 UTC by pandafy

2022-07-25 15:52 UTC, nemesisdesign approved these changes

2022-07-25 15:56 UTC, nemesisdesign reviewed
@pandafy is this something that needs the development version of OpenWISP Firmware Upgrader?

2022-07-25 15:58 UTC, pandafy commented
@nemesisdesign this requires openwisp-firmware-upgrader 1.0.1

2022-07-25 16:00 UTC, nemesisdesign requested changes
Then please increase the min version of that module accordingly.

2022-07-26 18:17 UTC, nemesisdesign approved these changes

2022-07-26 18:33 UTC, merged